### ISSUE TITLE
Support simple variables

### ISSUE THREAD

**Issue by shigedangao** [shigedangao/maomao#11]
Supporting simple variables could be nice. The following implementation could be done

- Create a vars.toml
- The var will contain variable that would only define simple toml definition (array, int, string)
- Define a special keyword which the parser will look for to replace. Preferable to avoid interpolation if anyone use a similar kind of argument definition

i.e 

**vars.toml**
```toml
replicas = 5
```

**deployment.toml**
```toml
# a deployment
kind = "workload::deployment"
name = "rusty"
metadata = { name = "rusty", tier = "backend" }

# container name rust
[workload]
    replicas = "`${replicas}`"
```
